[project]
name = "spotlight-segment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-genai>=1.15.0",
    "pydantic>=2.11.4",
    "pydantic-settings>=2.9.1",
    "yt-dlp>=2025.4.30",
]
